# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ZoomPhant Platform
tagline:          'One platform to rule all monitoring needs'
description:      'An awesome platform for monitoring and more, visit <a href="https://zoomphant.io" target="_blank">Zervice</a> for more. Made by <a href="https://twitter.com/zoomphant" target="_blank">@zoomphant</a>.'
url:              https://zoomphant.io
baseurl:          /

author:
  name:           'Zervice'
  url:            https://twitter.com/zervice

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ZoomPhant/zoomphant.github.io
