version: "3.5"

services:
  jekyll:
    build:
      context: ./
    ports:
      - 4000:4000
    extra_hosts:
      - "vm:0.0.0.0"
    volumes:
      - ../resource/index.md:/usr/src/app/index.md
      - ../resource/docs:/usr/src/app/docs
      - ../resource/assets/images:/usr/src/app/assets/images
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H ${HOST:-0.0.0.0} -t



